### ISSUE TITLE
TypeError: Cannot read properties of undefined

### ISSUE THREAD

**Issue by dVIAN13** [nicholasrobinson/homebridge-smartcielo#16] opened 2022-01-01 20:37 UTC
@nicholasrobinson, glad you're still around! I'm thinking some of the API calls have been modified recently. I have a MRCOOL DIY unit and prior to the below error, I was never able to make changes to the unit. It would read the temperature correctly from the API, but any attempt to make changes from within HK(Home App / HomeBridge), the request would fail, followed by the unit turning off.

`[1/1/2022, 12:26:19 PM] [MiniSplit] TypeError: Cannot read properties of undefined (reading 'listDevices')
    at /usr/lib/node_modules/homebridge-smartcielo/node_modules/node-smartcielo/SmartCielo.js:240:56
    at processTicksAndRejections (node:internal/process/task_queues:96:5)`

This error(warning) also comes up often:
    
    `[1/1/2022, 12:33:31 PM] [homebridge-smartcielo] This plugin slows down Homebridge. The read handler for the characteristic 'Current Heating Cooling State' didn't respond at all!. Please check that you properly call the callback! See https://git.io/JtMGR for more info.`

**Comment by aotearoacoder** [comment] 2022-01-23 16:41
Hi all, thanks for the work here! ... I am getting this same error on startup of the plugin:
```
[Cottage] TypeError: Cannot read properties of undefined (reading 'listDevices')
    at /Users/davem/.nvm/versions/node/v16.13.2/lib/node_modules/homebridge-smartcielo/node_modules/node-smartcielo/SmartCielo.js:240:56
```

Any help would be appreciated

**Comment by nullfx** [comment] 2022-01-26 03:54
same. installed one of these AC's about 6 months ago, have been seeing this issue since then (keep checking back to see if any updates have been made, looks like this is a dead plug in)

**Comment by aotearoacoder** [comment] 2022-01-26 05:07
The problem is in the underlying api connect package …

https://github.com/nicholasrobinson/node-smartcielo/blob/61963c3689ca7c5d2f7b1e20ed895220b2bebb2b/SmartCielo.js#L240

I plan on taking a look + seeing how hard it would be to allow multiple devices (I have a multi-zone Mr Cool, so would need that also). 

I would like to hear if any others have attempted fixing or attempted the multi-device step.

**Comment by nm2124** [comment] 2022-09-20 04:32
> The problem is in the underlying api connect package …
> 
> 
> 
> https://github.com/nicholasrobinson/node-smartcielo/blob/61963c3689ca7c5d2f7b1e20ed895220b2bebb2b/SmartCielo.js#L240
> 
> 
> 
> I plan on taking a look + seeing how hard it would be to allow multiple devices (I have a multi-zone Mr Cool, so would need that also). 
> 
> 
> 
> I would like to hear if any others have attempted fixing or attempted the multi-device step. 

Any luck here?

**Comment by isaac-webb** [comment] 2022-11-23 19:37
Hey all,
Installed a couple of these units in my house this summer and wanted HomeKit as well. Finally got a few days this week to dig into this problem. I took both of @nicholasrobinson's packages, updated them as best I could, and republished them. [`node-mrcool`](https://github.com/isaac-webb/node-mrcool) is the re-implemented library, and [`homebridge-mrcool`](https://github.com/isaac-webb/homebridge-mrcool) is the homebridge plugin. It seems to be working alright, but they are v1 packages, so probably some issues I haven't found. Please feel free to install and let me know how it works (and any bugs you find...!). In particular, I've only got the single zone 3rd gen units, so I'd be appreciative of input on multi-zone units @aotearoacoder.

**Comment by nullfx** [comment] 2022-11-28 21:07
> 

finally... thank you for the fix / update!!! i also only have the single zone though so unfortunately not any help on testing the multi-zone units.

**Comment by nicholasrobinson** [comment] 2023-07-23 22:16
Closing per https://github.com/nicholasrobinson/homebridge-smartcielo/issues/22

**Closed as completed by nicholasrobinson** 2023-07-23 22:16 UTC
